<?php
	$resource['host']='http://resource.dev.com/';
	$resource['alias']='assets/';
	$resource['common_js']="common/js/";
	$resource['common_css']="common/css/";
	$resource['common_img']="common/img/";
	$resource['js']="";
	$resource['css']="";
	$resource['img']="";
